#!/usr/bin/env python3

"""
Project Euler #288.

For any prime p the number N(p,q) is defined by N(p,q) = ∑_(n=0...q)T_n*p^n
with T_n generated by the following random number generator:

S0 = 290797
S_(n+1) = S_n^2 mod 50515093
T_n = S_n mod p

Let Nfac(p,q) be the factorial of N(p,q).
Let NF(p,q) be the number of factors p in Nfac(p,q).

You are given that NF(3,10000) mod 3^20=624955285.

Find NF(61,10^7) mod 61^10
"""

P, Q, N = 61, 10**7, 10
MOD = P**N

s = 290797
sum_1 = 0

for n in range(1, N + 1):
    s = s**2 % 50515093
    sum_1 += s % P * (P ** n - 1) // (P - 1)

sum_2 = 0

for n in range(N + 1, Q + 1):
    s = s**2 % 50515093
    sum_2 += s % P

sum_1 += sum_2 * (P ** N - 1) // (P - 1)

print(sum_1 % P ** N)
